language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

env:
  - MSBUILD_EXE="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe"

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode9.4
    - os: windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update --fix-missing ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y
    freeglut3-dev
    g++
    libasound2-dev
    libcurl4-openssl-dev
    libfreetype6-dev
    libjack-jackd2-dev
    libx11-dev
    libxcomposite-dev
    libxcursor-dev
    libxinerama-dev
    libxrandr-dev
    mesa-common-dev
    ladspa-sdk
    webkit2gtk-4.0
    libgtk-3-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update --fix-missing ; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3                       ; fi # give xvfb some time to start

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];      then $TRAVIS_BUILD_DIR/tests/mac/build_examples         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];    then $TRAVIS_BUILD_DIR/tests/linux/build_examples       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]];  then $TRAVIS_BUILD_DIR/tests/windows/build_examples.bat ; fi
